-- 第01章 環境構築と RDBMS の全体像

SELECT VERSION();
SHOW ENGINES;

CREATE TABLE t_innodb (id INT PRIMARY KEY) ENGINE=InnoDB;
CREATE TABLE t_myisam (id INT PRIMARY KEY) ENGINE=MyISAM;

START TRANSACTION;
INSERT INTO t_innodb VALUES (1);
ROLLBACK;
SELECT * FROM t_innodb;

START TRANSACTION;
INSERT INTO t_myisam VALUES (1);
ROLLBACK;
SELECT * FROM t_myisam;
SHOW WARNINGS;

DROP TABLE t_innodb, t_myisam;
